### ISSUE TITLE
Login screen - Text on login button does not appear (dark mode)

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-ios#703] opened 2022-12-08 13:04 UTC
### Steps to reproduce

1. Dark theme should be activated
2. On Login screen

#### What did you expect?
I should see the text on Login button
#### What happened instead?
Text on Login button does not appear
![IMG_2876](https://user-images.githubusercontent.com/3725676/206421870-377bbb7b-1b4b-4089-b8f7-0d969b0ea7c7.jpg)

### Your phone model

iphone 13

### Operating system version

iOS 16

### Application version

2.2.1

### Will you send logs?

No

**Comment by phlniji** [comment] 2022-12-08 13:22
Thanks @mcalinghee for this issue.

It is a duplicate of #693, and it has been fixed in Tchap v2.2.2. This version is currently in validation state at Apple for Tchap External beta testers (already available for internal ones).

**Closed by phlniji** 2022-12-08 13:22 UTC
